/**
 * Copyright (c) 2015 YCSB Contributors. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License. You
 * may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * permissions and limitations under the License. See accompanying
 * LICENSE file.
 */

CREATE TABLE userlog (
  person_id varchar primary key,
  lat varchar,
  lon varchar,
  timestamp varchar,
  zoom1 varchar,
  zoom2 varchar,
  zoom3 varchar,
  zoom4 varchar,
  zoom5 varchar,
  zoom6 varchar,
  zoom7 varchar,
  zoom8 varchar,
  zoom9 varchar,
  zoom10 varchar);
